[package]
name = "in-memory-dynamic-keys"
version = "0.1.0"
edition = "2021"

[dependencies]
cryptr = { path = "../.." }

anyhow = "1.0.75"
tokio = { version = "1.38.2", features = ["rt-multi-thread"] }
